# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_swdeimport.ui'
#
# Created: Sun Jun 23 12:28:48 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_swdeImport(object):
    def setupUi(self, swdeImport):
        swdeImport.setObjectName(_fromUtf8("swdeImport"))
        swdeImport.resize(557, 583)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/swdeimport/swde-plug-import-22b.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        swdeImport.setWindowIcon(icon)
        self.verticalLayout_16 = QtGui.QVBoxLayout(swdeImport)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.tabWidget = QtGui.QTabWidget(swdeImport)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabSettings)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tabSettings)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tabDBSettings = QtGui.QWidget()
        self.tabDBSettings.setObjectName(_fromUtf8("tabDBSettings"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabDBSettings)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label = QtGui.QLabel(self.tabDBSettings)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_7.addWidget(self.label)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.tabDBSettings)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.leditDBServer = QtGui.QLineEdit(self.tabDBSettings)
        self.leditDBServer.setObjectName(_fromUtf8("leditDBServer"))
        self.horizontalLayout_4.addWidget(self.leditDBServer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.tabDBSettings)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.leditDBPort = QtGui.QLineEdit(self.tabDBSettings)
        self.leditDBPort.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leditDBPort.setObjectName(_fromUtf8("leditDBPort"))
        self.horizontalLayout_5.addWidget(self.leditDBPort)
        self.label_19 = QtGui.QLabel(self.tabDBSettings)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_5.addWidget(self.label_19)
        self.leditDBBaseName = QtGui.QLineEdit(self.tabDBSettings)
        self.leditDBBaseName.setObjectName(_fromUtf8("leditDBBaseName"))
        self.horizontalLayout_5.addWidget(self.leditDBBaseName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.tabDBSettings)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.leditDBUser = QtGui.QLineEdit(self.tabDBSettings)
        self.leditDBUser.setObjectName(_fromUtf8("leditDBUser"))
        self.horizontalLayout_6.addWidget(self.leditDBUser)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_5 = QtGui.QLabel(self.tabDBSettings)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.leditDBPassword = QtGui.QLineEdit(self.tabDBSettings)
        self.leditDBPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.leditDBPassword.setObjectName(_fromUtf8("leditDBPassword"))
        self.horizontalLayout_6.addWidget(self.leditDBPassword)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.line_2 = QtGui.QFrame(self.tabDBSettings)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_7.addWidget(self.line_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.tabDBSettings)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.leditAdminName = QtGui.QLineEdit(self.tabDBSettings)
        self.leditAdminName.setObjectName(_fromUtf8("leditAdminName"))
        self.horizontalLayout_8.addWidget(self.leditAdminName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_7 = QtGui.QLabel(self.tabDBSettings)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        self.leditAdminPswd = QtGui.QLineEdit(self.tabDBSettings)
        self.leditAdminPswd.setEchoMode(QtGui.QLineEdit.Password)
        self.leditAdminPswd.setObjectName(_fromUtf8("leditAdminPswd"))
        self.horizontalLayout_9.addWidget(self.leditAdminPswd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pbtnDBSaveSettings = QtGui.QPushButton(self.tabDBSettings)
        self.pbtnDBSaveSettings.setObjectName(_fromUtf8("pbtnDBSaveSettings"))
        self.verticalLayout_4.addWidget(self.pbtnDBSaveSettings)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.line = QtGui.QFrame(self.tabDBSettings)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_7.addWidget(self.line)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_17 = QtGui.QLabel(self.tabDBSettings)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_7.addWidget(self.label_17)
        self.leditTemplate = QtGui.QLineEdit(self.tabDBSettings)
        self.leditTemplate.setObjectName(_fromUtf8("leditTemplate"))
        self.horizontalLayout_7.addWidget(self.leditTemplate)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_18 = QtGui.QLabel(self.tabDBSettings)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_11.addWidget(self.label_18)
        self.leditSRID = QtGui.QLineEdit(self.tabDBSettings)
        self.leditSRID.setObjectName(_fromUtf8("leditSRID"))
        self.horizontalLayout_11.addWidget(self.leditSRID)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.groupBox = QtGui.QGroupBox(self.tabDBSettings)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.rdbtnPostgis15 = QtGui.QRadioButton(self.groupBox)
        self.rdbtnPostgis15.setChecked(True)
        self.rdbtnPostgis15.setObjectName(_fromUtf8("rdbtnPostgis15"))
        self.horizontalLayout_25.addWidget(self.rdbtnPostgis15)
        self.rdbtnPostgis20 = QtGui.QRadioButton(self.groupBox)
        self.rdbtnPostgis20.setObjectName(_fromUtf8("rdbtnPostgis20"))
        self.horizontalLayout_25.addWidget(self.rdbtnPostgis20)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_25)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_27.addLayout(self.verticalLayout_5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem2)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.pbtnCreateSWDEDB = QtGui.QPushButton(self.tabDBSettings)
        self.pbtnCreateSWDEDB.setObjectName(_fromUtf8("pbtnCreateSWDEDB"))
        self.verticalLayout_6.addWidget(self.pbtnCreateSWDEDB)
        self.horizontalLayout_27.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.tabWidget_2.addTab(self.tabDBSettings, _fromUtf8(""))
        self.tabImportOptions = QtGui.QWidget()
        self.tabImportOptions.setObjectName(_fromUtf8("tabImportOptions"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.tabImportOptions)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.chckTransform = QtGui.QCheckBox(self.tabImportOptions)
        self.chckTransform.setChecked(True)
        self.chckTransform.setObjectName(_fromUtf8("chckTransform"))
        self.verticalLayout_21.addWidget(self.chckTransform)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_8 = QtGui.QLabel(self.tabImportOptions)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_17.addWidget(self.label_8)
        self.cmbPyprojFrom = QtGui.QComboBox(self.tabImportOptions)
        self.cmbPyprojFrom.setObjectName(_fromUtf8("cmbPyprojFrom"))
        self.verticalLayout_17.addWidget(self.cmbPyprojFrom)
        self.verticalLayout_21.addLayout(self.verticalLayout_17)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_9 = QtGui.QLabel(self.tabImportOptions)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_19.addWidget(self.label_9)
        self.cmbPyprojTo = QtGui.QComboBox(self.tabImportOptions)
        self.cmbPyprojTo.setObjectName(_fromUtf8("cmbPyprojTo"))
        self.verticalLayout_19.addWidget(self.cmbPyprojTo)
        self.verticalLayout_21.addLayout(self.verticalLayout_19)
        self.verticalLayout_22.addLayout(self.verticalLayout_21)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_13 = QtGui.QLabel(self.tabImportOptions)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_18.addWidget(self.label_13)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rdbtnTestowyJEW = QtGui.QRadioButton(self.tabImportOptions)
        self.rdbtnTestowyJEW.setChecked(True)
        self.rdbtnTestowyJEW.setObjectName(_fromUtf8("rdbtnTestowyJEW"))
        self.horizontalLayout_2.addWidget(self.rdbtnTestowyJEW)
        self.rdbtnTestowyOBR = QtGui.QRadioButton(self.tabImportOptions)
        self.rdbtnTestowyOBR.setObjectName(_fromUtf8("rdbtnTestowyOBR"))
        self.horizontalLayout_2.addWidget(self.rdbtnTestowyOBR)
        self.rdbtnTestowyDZE = QtGui.QRadioButton(self.tabImportOptions)
        self.rdbtnTestowyDZE.setObjectName(_fromUtf8("rdbtnTestowyDZE"))
        self.horizontalLayout_2.addWidget(self.rdbtnTestowyDZE)
        self.verticalLayout_18.addLayout(self.horizontalLayout_2)
        self.verticalLayout_22.addLayout(self.verticalLayout_18)
        self.grbxImportTable = QtGui.QGroupBox(self.tabImportOptions)
        self.grbxImportTable.setFlat(False)
        self.grbxImportTable.setCheckable(False)
        self.grbxImportTable.setChecked(False)
        self.grbxImportTable.setObjectName(_fromUtf8("grbxImportTable"))
        self.gridLayout = QtGui.QGridLayout(self.grbxImportTable)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chckG5udw = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5udw.setChecked(True)
        self.chckG5udw.setObjectName(_fromUtf8("chckG5udw"))
        self.gridLayout.addWidget(self.chckG5udw, 1, 1, 1, 1)
        self.checkBox_20 = QtGui.QCheckBox(self.grbxImportTable)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.gridLayout.addWidget(self.checkBox_20, 3, 3, 1, 1)
        self.chckG5lkl = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5lkl.setObjectName(_fromUtf8("chckG5lkl"))
        self.gridLayout.addWidget(self.chckG5lkl, 0, 3, 1, 1)
        self.chckG5dze = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5dze.setChecked(True)
        self.chckG5dze.setObjectName(_fromUtf8("chckG5dze"))
        self.gridLayout.addWidget(self.chckG5dze, 0, 0, 1, 1)
        self.chckG5jdr = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5jdr.setChecked(True)
        self.chckG5jdr.setObjectName(_fromUtf8("chckG5jdr"))
        self.gridLayout.addWidget(self.chckG5jdr, 3, 0, 1, 1)
        self.chckG5ins = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5ins.setChecked(True)
        self.chckG5ins.setObjectName(_fromUtf8("chckG5ins"))
        self.gridLayout.addWidget(self.chckG5ins, 3, 1, 1, 1)
        self.chckG5obr = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5obr.setChecked(True)
        self.chckG5obr.setObjectName(_fromUtf8("chckG5obr"))
        self.gridLayout.addWidget(self.chckG5obr, 1, 0, 1, 1)
        self.chckG5mlz = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5mlz.setChecked(True)
        self.chckG5mlz.setObjectName(_fromUtf8("chckG5mlz"))
        self.gridLayout.addWidget(self.chckG5mlz, 4, 1, 1, 1)
        self.checkBox_19 = QtGui.QCheckBox(self.grbxImportTable)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.gridLayout.addWidget(self.checkBox_19, 4, 3, 1, 1)
        self.chckG5uzg = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5uzg.setChecked(True)
        self.chckG5uzg.setObjectName(_fromUtf8("chckG5uzg"))
        self.gridLayout.addWidget(self.chckG5uzg, 2, 2, 1, 1)
        self.chckG5osf = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5osf.setChecked(True)
        self.chckG5osf.setObjectName(_fromUtf8("chckG5osf"))
        self.gridLayout.addWidget(self.chckG5osf, 2, 1, 1, 1)
        self.chckG5kkl = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5kkl.setChecked(True)
        self.chckG5kkl.setObjectName(_fromUtf8("chckG5kkl"))
        self.gridLayout.addWidget(self.chckG5kkl, 2, 3, 1, 1)
        self.chckG5udz = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5udz.setChecked(True)
        self.chckG5udz.setObjectName(_fromUtf8("chckG5udz"))
        self.gridLayout.addWidget(self.chckG5udz, 0, 1, 1, 1)
        self.chckG5klu = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5klu.setChecked(True)
        self.chckG5klu.setObjectName(_fromUtf8("chckG5klu"))
        self.gridLayout.addWidget(self.chckG5klu, 1, 2, 1, 1)
        self.chckG5zmn = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5zmn.setObjectName(_fromUtf8("chckG5zmn"))
        self.gridLayout.addWidget(self.chckG5zmn, 1, 3, 1, 1)
        self.chckG5jew = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5jew.setChecked(True)
        self.chckG5jew.setObjectName(_fromUtf8("chckG5jew"))
        self.gridLayout.addWidget(self.chckG5jew, 2, 0, 1, 1)
        self.chckG5adr = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5adr.setChecked(True)
        self.chckG5adr.setObjectName(_fromUtf8("chckG5adr"))
        self.gridLayout.addWidget(self.chckG5adr, 4, 0, 1, 1)
        self.chckG5dok = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5dok.setChecked(True)
        self.chckG5dok.setObjectName(_fromUtf8("chckG5dok"))
        self.gridLayout.addWidget(self.chckG5dok, 3, 2, 1, 1)
        self.chckG5bud = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5bud.setObjectName(_fromUtf8("chckG5bud"))
        self.gridLayout.addWidget(self.chckG5bud, 4, 2, 1, 1)
        self.chckG5osz = QtGui.QCheckBox(self.grbxImportTable)
        self.chckG5osz.setChecked(True)
        self.chckG5osz.setObjectName(_fromUtf8("chckG5osz"))
        self.gridLayout.addWidget(self.chckG5osz, 0, 2, 1, 1)
        self.verticalLayout_22.addWidget(self.grbxImportTable)
        self.horizontalLayout_24.addLayout(self.verticalLayout_22)
        self.tabWidget_2.addTab(self.tabImportOptions, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/swdeimport/preferences-other.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabSettings, icon1, _fromUtf8(""))
        self.tabImport = QtGui.QWidget()
        self.tabImport.setObjectName(_fromUtf8("tabImport"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.tabImport)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_14 = QtGui.QLabel(self.tabImport)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_20.addWidget(self.label_14)
        self.leditSWDEFile = QtGui.QLineEdit(self.tabImport)
        self.leditSWDEFile.setObjectName(_fromUtf8("leditSWDEFile"))
        self.horizontalLayout_20.addWidget(self.leditSWDEFile)
        self.tbtnWybierzSWDEFile = QtGui.QToolButton(self.tabImport)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/swdeimport/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtnWybierzSWDEFile.setIcon(icon2)
        self.tbtnWybierzSWDEFile.setObjectName(_fromUtf8("tbtnWybierzSWDEFile"))
        self.horizontalLayout_20.addWidget(self.tbtnWybierzSWDEFile)
        self.horizontalLayout_20.setStretch(1, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_20)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_10 = QtGui.QLabel(self.tabImport)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_8.addWidget(self.label_10)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.grBxKodowanieSWDE = QtGui.QGroupBox(self.tabImport)
        self.grBxKodowanieSWDE.setObjectName(_fromUtf8("grBxKodowanieSWDE"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.grBxKodowanieSWDE)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.rdbtnKodowanieISO = QtGui.QRadioButton(self.grBxKodowanieSWDE)
        self.rdbtnKodowanieISO.setChecked(True)
        self.rdbtnKodowanieISO.setObjectName(_fromUtf8("rdbtnKodowanieISO"))
        self.horizontalLayout_12.addWidget(self.rdbtnKodowanieISO)
        self.rdbtnKodowanieWindows = QtGui.QRadioButton(self.grBxKodowanieSWDE)
        self.rdbtnKodowanieWindows.setObjectName(_fromUtf8("rdbtnKodowanieWindows"))
        self.horizontalLayout_12.addWidget(self.rdbtnKodowanieWindows)
        self.rdbtnKodowanieUTF = QtGui.QRadioButton(self.grBxKodowanieSWDE)
        self.rdbtnKodowanieUTF.setObjectName(_fromUtf8("rdbtnKodowanieUTF"))
        self.horizontalLayout_12.addWidget(self.rdbtnKodowanieUTF)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13.addWidget(self.grBxKodowanieSWDE)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.verticalLayout_14.addLayout(self.verticalLayout_8)
        self.line_3 = QtGui.QFrame(self.tabImport)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_14.addWidget(self.line_3)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_11 = QtGui.QLabel(self.tabImport)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_13.addWidget(self.label_11)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.lblPlikLines = QtGui.QLabel(self.tabImport)
        self.lblPlikLines.setObjectName(_fromUtf8("lblPlikLines"))
        self.horizontalLayout_16.addWidget(self.lblPlikLines)
        self.leditLineInFile = QtGui.QLineEdit(self.tabImport)
        self.leditLineInFile.setReadOnly(True)
        self.leditLineInFile.setObjectName(_fromUtf8("leditLineInFile"))
        self.horizontalLayout_16.addWidget(self.leditLineInFile)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_12 = QtGui.QLabel(self.tabImport)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_15.addWidget(self.label_12)
        self.leditIDZD = QtGui.QLineEdit(self.tabImport)
        self.leditIDZD.setObjectName(_fromUtf8("leditIDZD"))
        self.horizontalLayout_15.addWidget(self.leditIDZD)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_16 = QtGui.QLabel(self.tabImport)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_19.addWidget(self.label_16)
        self.leditIloscPZG = QtGui.QLineEdit(self.tabImport)
        self.leditIloscPZG.setReadOnly(True)
        self.leditIloscPZG.setObjectName(_fromUtf8("leditIloscPZG"))
        self.horizontalLayout_19.addWidget(self.leditIloscPZG)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.pbtnAnalizaWykonaj = QtGui.QPushButton(self.tabImport)
        self.pbtnAnalizaWykonaj.setObjectName(_fromUtf8("pbtnAnalizaWykonaj"))
        self.verticalLayout_10.addWidget(self.pbtnAnalizaWykonaj)
        self.horizontalLayout_21.addLayout(self.verticalLayout_10)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_20.addLayout(self.verticalLayout_14)
        self.line_4 = QtGui.QFrame(self.tabImport)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_20.addWidget(self.line_4)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.grbxRodzImportu = QtGui.QGroupBox(self.tabImport)
        self.grbxRodzImportu.setObjectName(_fromUtf8("grbxRodzImportu"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.grbxRodzImportu)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.rdbtnZwyklyImport = QtGui.QRadioButton(self.grbxRodzImportu)
        self.rdbtnZwyklyImport.setChecked(True)
        self.rdbtnZwyklyImport.setObjectName(_fromUtf8("rdbtnZwyklyImport"))
        self.horizontalLayout_17.addWidget(self.rdbtnZwyklyImport)
        self.rdbtnImportTestowy = QtGui.QRadioButton(self.grbxRodzImportu)
        self.rdbtnImportTestowy.setObjectName(_fromUtf8("rdbtnImportTestowy"))
        self.horizontalLayout_17.addWidget(self.rdbtnImportTestowy)
        self.rdbtnAktualizacja = QtGui.QRadioButton(self.grbxRodzImportu)
        self.rdbtnAktualizacja.setObjectName(_fromUtf8("rdbtnAktualizacja"))
        self.horizontalLayout_17.addWidget(self.rdbtnAktualizacja)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18.addWidget(self.grbxRodzImportu)
        self.pbtnImportuj = QtGui.QPushButton(self.tabImport)
        self.pbtnImportuj.setObjectName(_fromUtf8("pbtnImportuj"))
        self.horizontalLayout_18.addWidget(self.pbtnImportuj)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.verticalLayout_20.addLayout(self.verticalLayout_12)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/swdeimport/system-run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabImport, icon3, _fromUtf8(""))
        self.tabSDEInfo = QtGui.QWidget()
        self.tabSDEInfo.setObjectName(_fromUtf8("tabSDEInfo"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.tabSDEInfo)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_15 = QtGui.QLabel(self.tabSDEInfo)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_15.addWidget(self.label_15)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem7)
        self.pbtnSWDEHeaderInfo = QtGui.QPushButton(self.tabSDEInfo)
        self.pbtnSWDEHeaderInfo.setObjectName(_fromUtf8("pbtnSWDEHeaderInfo"))
        self.horizontalLayout_22.addWidget(self.pbtnSWDEHeaderInfo)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.pbtnSWDEHeaderFull = QtGui.QPushButton(self.tabSDEInfo)
        self.pbtnSWDEHeaderFull.setObjectName(_fromUtf8("pbtnSWDEHeaderFull"))
        self.horizontalLayout_22.addWidget(self.pbtnSWDEHeaderFull)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.horizontalLayout_22.setStretch(1, 1)
        self.horizontalLayout_22.setStretch(3, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_22)
        self.peditSWDEHeader = QtGui.QTextBrowser(self.tabSDEInfo)
        self.peditSWDEHeader.setMinimumSize(QtCore.QSize(0, 260))
        self.peditSWDEHeader.setObjectName(_fromUtf8("peditSWDEHeader"))
        self.verticalLayout_15.addWidget(self.peditSWDEHeader)
        self.horizontalLayout_23.addLayout(self.verticalLayout_15)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/swdeimport/documentation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabSDEInfo, icon4, _fromUtf8(""))
        self.verticalLayout_16.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.peditOutput = QtGui.QPlainTextEdit(swdeImport)
        self.peditOutput.setObjectName(_fromUtf8("peditOutput"))
        self.horizontalLayout.addWidget(self.peditOutput)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.pbtnClose = QtGui.QPushButton(swdeImport)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/swdeimport/application-exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnClose.setIcon(icon5)
        self.pbtnClose.setObjectName(_fromUtf8("pbtnClose"))
        self.verticalLayout.addWidget(self.pbtnClose)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_16.addLayout(self.horizontalLayout)

        self.retranslateUi(swdeImport)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QObject.connect(self.pbtnClose, QtCore.SIGNAL(_fromUtf8("clicked()")), swdeImport.hide)
        QtCore.QMetaObject.connectSlotsByName(swdeImport)

    def retranslateUi(self, swdeImport):
        swdeImport.setWindowTitle(QtGui.QApplication.translate("swdeImport", "swdeImport", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("swdeImport", "Uwaga - ustawienia poniższe dotyczą wszystkich wtyczek z grupy SWDE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("swdeImport", "Serwer pgSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("swdeImport", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.leditDBPort.setText(QtGui.QApplication.translate("swdeImport", "5432", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("swdeImport", "Baza", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("swdeImport", "Użytkownik", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("swdeImport", "hasło", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("swdeImport", "Admin (user)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("swdeImport", "Admin password", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnDBSaveSettings.setText(QtGui.QApplication.translate("swdeImport", "Zapisz ustawienia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("swdeImport", "Template", None, QtGui.QApplication.UnicodeUTF8))
        self.leditTemplate.setText(QtGui.QApplication.translate("swdeImport", "postgis_template", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("swdeImport", "SRID", None, QtGui.QApplication.UnicodeUTF8))
        self.leditSRID.setToolTip(QtGui.QApplication.translate("swdeImport", "<html><head/><body><p>identyfikator układu odniesienia w bazach postgisa. Odpowiada numerowi kodu epsg. Może być ustawiony jako &quot;-1&quot; - czyli nieokreślony</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.leditSRID.setText(QtGui.QApplication.translate("swdeImport", "2180", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("swdeImport", "Wersja Postgisa", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnPostgis15.setText(QtGui.QApplication.translate("swdeImport", "1.5", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnPostgis20.setText(QtGui.QApplication.translate("swdeImport", "2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnCreateSWDEDB.setText(QtGui.QApplication.translate("swdeImport", "Utwórz bazę swde", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabDBSettings), QtGui.QApplication.translate("swdeImport", "Ustawienia bazy danych", None, QtGui.QApplication.UnicodeUTF8))
        self.chckTransform.setText(QtGui.QApplication.translate("swdeImport", "Zmiana przestrzennego układu odniesienia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("swdeImport", "Układ odniesienia w pliku SWDE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("swdeImport", "Układ odniesienia w docelowej bazie ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("swdeImport", "Opcje importu testowego:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnTestowyJEW.setText(QtGui.QApplication.translate("swdeImport", "jednostka ewid.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnTestowyOBR.setText(QtGui.QApplication.translate("swdeImport", "obręby", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnTestowyDZE.setText(QtGui.QApplication.translate("swdeImport", "działki", None, QtGui.QApplication.UnicodeUTF8))
        self.grbxImportTable.setTitle(QtGui.QApplication.translate("swdeImport", "Wybierz tabele do importu:", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5udw.setText(QtGui.QApplication.translate("swdeImport", "g5udw", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_20.setText(QtGui.QApplication.translate("swdeImport", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5lkl.setText(QtGui.QApplication.translate("swdeImport", "g5lkl", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5dze.setText(QtGui.QApplication.translate("swdeImport", "g5dze", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5jdr.setText(QtGui.QApplication.translate("swdeImport", "g5jdr", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5ins.setText(QtGui.QApplication.translate("swdeImport", "g5ins", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5obr.setText(QtGui.QApplication.translate("swdeImport", "g5obr", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5mlz.setText(QtGui.QApplication.translate("swdeImport", "g5mlz", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_19.setText(QtGui.QApplication.translate("swdeImport", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5uzg.setText(QtGui.QApplication.translate("swdeImport", "g5uzg", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5osf.setText(QtGui.QApplication.translate("swdeImport", "g5osf", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5kkl.setText(QtGui.QApplication.translate("swdeImport", "g5kkl", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5udz.setText(QtGui.QApplication.translate("swdeImport", "g5udz", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5klu.setText(QtGui.QApplication.translate("swdeImport", "g5klu", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5zmn.setText(QtGui.QApplication.translate("swdeImport", "g5zmn", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5jew.setText(QtGui.QApplication.translate("swdeImport", "g5jew", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5adr.setText(QtGui.QApplication.translate("swdeImport", "g5adr", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5dok.setText(QtGui.QApplication.translate("swdeImport", "g5dok", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5bud.setText(QtGui.QApplication.translate("swdeImport", "g5bud", None, QtGui.QApplication.UnicodeUTF8))
        self.chckG5osz.setText(QtGui.QApplication.translate("swdeImport", "g5osz", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabImportOptions), QtGui.QApplication.translate("swdeImport", "Opcje importu", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), QtGui.QApplication.translate("swdeImport", "Ustawienia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("swdeImport", "Wybierz plik:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbtnWybierzSWDEFile.setText(QtGui.QApplication.translate("swdeImport", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("swdeImport", "Krok 1. Określenie kodowania pliku wejściowego swde. Po wybraniu odpowiedniej opcji możesz sprawdzić jej poprawność wczytując pierwszych 1000 linii - na zakładce >Plik SWDE<", None, QtGui.QApplication.UnicodeUTF8))
        self.grBxKodowanieSWDE.setTitle(QtGui.QApplication.translate("swdeImport", "Kodowanie pliku swde", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnKodowanieISO.setText(QtGui.QApplication.translate("swdeImport", "ISO8859-2", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnKodowanieWindows.setText(QtGui.QApplication.translate("swdeImport", "WINDOWS-1250", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnKodowanieUTF.setText(QtGui.QApplication.translate("swdeImport", "UTF8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("swdeImport", "Krok 2. Analiza pliku swde (długość, jednostka ewidencyjna)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPlikLines.setText(QtGui.QApplication.translate("swdeImport", "Plik zawiera linii:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("swdeImport", "Identyfikator zbioru:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("swdeImport", "Ilość punktów zał. granicy", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnAnalizaWykonaj.setText(QtGui.QApplication.translate("swdeImport", "Wykonaj...", None, QtGui.QApplication.UnicodeUTF8))
        self.grbxRodzImportu.setTitle(QtGui.QApplication.translate("swdeImport", "Krok 3. Rodzaj importu", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnZwyklyImport.setText(QtGui.QApplication.translate("swdeImport", "Zwykły", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnImportTestowy.setText(QtGui.QApplication.translate("swdeImport", "Testowy", None, QtGui.QApplication.UnicodeUTF8))
        self.rdbtnAktualizacja.setText(QtGui.QApplication.translate("swdeImport", "Aktualizacja", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnImportuj.setText(QtGui.QApplication.translate("swdeImport", "Importuj...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImport), QtGui.QApplication.translate("swdeImport", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("swdeImport", "Poniżej zostaną wyświetlone najważniejsze informacje zawarte w części nagłówkowej wybranego z sekcji >Import< pliku SWDE. Możesz również wyświetlić pierwszych 1000 linii pliku (przydatne przy sprawdzeniu czy zostało właściwie określone kodowanie pliku na zakładce >Import<).", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnSWDEHeaderInfo.setText(QtGui.QApplication.translate("swdeImport", "Tylko informacja", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnSWDEHeaderFull.setText(QtGui.QApplication.translate("swdeImport", "Pierwsze 1000 linii", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSDEInfo), QtGui.QApplication.translate("swdeImport", "Plik SWDE", None, QtGui.QApplication.UnicodeUTF8))
        self.pbtnClose.setText(QtGui.QApplication.translate("swdeImport", "Zamknij", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
